# Transform localizations from TranslateWiki.net
#
# As of late 2020, TranslateWiki creates PRs automatically, in line with
# how they work with other repos. However, the strings still need to be
# translated to work well with the iOS app. This script runs when a new PR
# is created by TranslateWiki, to add everything the app needs to the PR.
#
name: Import localizations from TranslateWiki

on:
  push:
    branches:
        - twn
  workflow_dispatch:

jobs:
  update-localizations:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: false

    - name: Update localizations
      continue-on-error: true
      env:
        APPS_BOT_TOKEN: ${{ secrets.APPS_BOT_TOKEN }}
      run: |
        $GITHUB_WORKSPACE/scripts/localization $GITHUB_WORKSPACE
        git config user.name wmf-apps-ci
        git config user.email wmf-apps-ci@users.noreply.github.com
        git add .
        git commit -m "Import translations from TranslateWiki"
        git push https://x-access-token:${APPS_BOT_TOKEN}@github.com/${{ github.repository }}
