name: Benchmark Mastodon

on:
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: benchmark-mastodon-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  cache-uploads:
    name: Clean build with cache uploads
    runs-on: namespace-profile-default-macos
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Authenticate Tuist
        working-directory: mastodon-ios
        run: TUIST_URL="https://staging.tuist.dev" tuist auth login --email tuistrocks@tuist.dev --password ${{ secrets.TUIST_TEST_ACCOUNT_PASSWORD }}

      - name: Setup Tuist Cache
        working-directory: mastodon-ios
        run: tuist setup cache

      - name: Setup Build Environment
        working-directory: mastodon-ios
        run: exec ./.github/scripts/setup.sh

      - name: Benchmark clean build with cache uploads
        working-directory: mastodon-ios
        run: |
          hyperfine --warmup 1 --runs 3 \
            --prepare 'rm -rf ~/Library/Developer/Xcode/DerivedData && xcodebuild -project Mastodon.xcodeproj -scheme Mastodon -resolvePackageDependencies && ../tuist-setup-temp-project' \
            'HANDLE="$(cat .tuist-temp-org)_$(cat .tuist-temp-project)" && xcodebuild -project Mastodon.xcodeproj -scheme Mastodon -destination "platform=iOS Simulator,name=iPhone 17" build COMPILATION_CACHE_ENABLE_CACHING="YES" COMPILATION_CACHE_ENABLE_PLUGIN="YES" COMPILATION_CACHE_REMOTE_SERVICE_PATH="$HOME/.local/state/tuist/$HANDLE.sock"' \
            --conclude '../tuist-cleanup-temp-project' \
            --show-output

  pre-warmed:
    name: Clean build with pre-warmed cache
    runs-on: namespace-profile-default-macos
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Authenticate Tuist
        working-directory: mastodon-ios
        run: TUIST_URL="https://staging.tuist.dev" tuist auth login --email tuistrocks@tuist.dev --password ${{ secrets.TUIST_TEST_ACCOUNT_PASSWORD }}

      - name: Setup Tuist Cache
        working-directory: mastodon-ios
        run: tuist setup cache

      - name: Setup Build Environment
        working-directory: mastodon-ios
        run: exec ./.github/scripts/setup.sh

      - name: Benchmark clean build with pre-warmed cache
        working-directory: mastodon-ios
        run: |
          hyperfine --warmup 1 --runs 3 \
            --setup 'xcodebuild -project Mastodon.xcodeproj -scheme Mastodon -destination "platform=iOS Simulator,name=iPhone 17" build COMPILATION_CACHE_ENABLE_CACHING="YES" COMPILATION_CACHE_ENABLE_PLUGIN="YES" COMPILATION_CACHE_REMOTE_SERVICE_PATH="$HOME/.local/state/tuist/tuist_mastodon.sock"' \
            --prepare 'rm -rf ~/Library/Developer/Xcode/DerivedData && xcodebuild -project Mastodon.xcodeproj -scheme Mastodon -resolvePackageDependencies' \
            'xcodebuild -project Mastodon.xcodeproj -scheme Mastodon -destination "platform=iOS Simulator,name=iPhone 17" build COMPILATION_CACHE_ENABLE_CACHING="YES" COMPILATION_CACHE_ENABLE_PLUGIN="YES" COMPILATION_CACHE_REMOTE_SERVICE_PATH="$HOME/.local/state/tuist/tuist_mastodon.sock"' \
            --show-output

  no-cache:
    name: Clean build without caching
    runs-on: namespace-profile-default-macos
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Authenticate Tuist
        working-directory: mastodon-ios
        run: TUIST_URL="https://staging.tuist.dev" tuist auth login --email tuistrocks@tuist.dev --password ${{ secrets.TUIST_TEST_ACCOUNT_PASSWORD }}

      - name: Setup Tuist Cache
        working-directory: mastodon-ios
        run: tuist setup cache

      - name: Setup Build Environment
        working-directory: mastodon-ios
        run: exec ./.github/scripts/setup.sh

      - name: Benchmark clean build without caching
        working-directory: mastodon-ios
        run: |
          hyperfine --warmup 1 --runs 3 \
            --prepare 'rm -rf ~/Library/Developer/Xcode/DerivedData && xcodebuild -project Mastodon.xcodeproj -scheme Mastodon -resolvePackageDependencies' \
            'xcodebuild -project Mastodon.xcodeproj -scheme Mastodon -destination "platform=iOS Simulator,name=iPhone 17" build COMPILATION_CACHE_ENABLE_CACHING=NO' \
            --show-output

  local-cache:
    name: Clean build with local caching
    runs-on: namespace-profile-default-macos
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Authenticate Tuist
        working-directory: mastodon-ios
        run: TUIST_URL="https://staging.tuist.dev" tuist auth login --email tuistrocks@tuist.dev --password ${{ secrets.TUIST_TEST_ACCOUNT_PASSWORD }}

      - name: Setup Tuist Cache
        working-directory: mastodon-ios
        run: tuist setup cache

      - name: Setup Build Environment
        working-directory: mastodon-ios
        run: exec ./.github/scripts/setup.sh

      - name: Benchmark clean build with local caching
        working-directory: mastodon-ios
        run: |
          hyperfine --warmup 1 --runs 3 \
            --setup 'rm -rf ~/Library/Developer/Xcode/DerivedData' \
            --prepare 'xcodebuild -project Mastodon.xcodeproj -scheme Mastodon -destination "platform=iOS Simulator,name=iPhone 17" clean && xcodebuild -project Mastodon.xcodeproj -scheme Mastodon -resolvePackageDependencies' \
            'xcodebuild -project Mastodon.xcodeproj -scheme Mastodon -destination "platform=iOS Simulator,name=iPhone 17" build COMPILATION_CACHE_ENABLE_CACHING="YES" COMPILATION_CACHE_ENABLE_PLUGIN=NO' \
            --show-output
