name: Benchmark

on:
  push:

permissions:
  contents: read

concurrency:
  group: benchmark-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  benchmark-cache:
    name: Benchmark Tuist Cache
    runs-on: namespace-profile-default-macos
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Tuist Cache
        working-directory: xcode_project_with_cache
        env:
          TUIST_CONFIG_TOKEN: ${{ secrets.TUIST_CAS_STAGING_TOKEN }}
        run: tuist setup cache

      # Benchmark 1: Clean build with cache uploads
      - name: Benchmark clean build with cache uploads
        working-directory: xcode_project_with_cache
        env:
          TUIST_CONFIG_TOKEN: ${{ secrets.TUIST_CAS_STAGING_TOKEN }}
        run: |
          hyperfine --warmup 1 --runs 3 \
            --prepare 'rm -rf ~/Library/Developer/Xcode/DerivedData && tuist clean --remote' \
            'xcodebuild -project App.xcodeproj -scheme App -destination "platform=iOS Simulator,name=iPhone 17" build' \
            --show-output

      # Benchmark 2: Clean build with pre-warmed cache
      - name: Benchmark clean build with pre-warmed cache
        working-directory: xcode_project_with_cache
        env:
          TUIST_CONFIG_TOKEN: ${{ secrets.TUIST_CAS_STAGING_TOKEN }}
        run: |
          hyperfine --warmup 1 --runs 3 \
            --setup 'tuist clean --remote && xcodebuild -project App.xcodeproj -scheme App -destination "platform=iOS Simulator,name=iPhone 17" build' \
            --prepare 'rm -rf ~/Library/Developer/Xcode/DerivedData' \
            'xcodebuild -project App.xcodeproj -scheme App -destination "platform=iOS Simulator,name=iPhone 17" build' \
            --show-output

      # Benchmark 3: Clean build without caching
      - name: Benchmark clean build without caching
        working-directory: xcode_project_with_cache
        env:
          TUIST_CONFIG_TOKEN: ${{ secrets.TUIST_CAS_STAGING_TOKEN }}
        run: |
          hyperfine --warmup 1 --runs 3 \
            --prepare 'rm -rf ~/Library/Developer/Xcode/DerivedData' \
            'xcodebuild -project App.xcodeproj -scheme App -destination "platform=iOS Simulator,name=iPhone 17" build COMPILATION_CACHE_ENABLE_CACHING=NO' \
            --show-output

      # Benchmark 3: Clean build with local caching
      - name: Benchmark clean build without caching
        working-directory: xcode_project_with_cache
        env:
          TUIST_CONFIG_TOKEN: ${{ secrets.TUIST_CAS_STAGING_TOKEN }}
        run: |
          hyperfine --warmup 1 --runs 3 \
            --setup 'rm -rf ~/Library/Developer/Xcode/DerivedData' \
            'xcodebuild -project App.xcodeproj -scheme App -destination "platform=iOS Simulator,name=iPhone 17" build COMPILATION_CACHE_ENABLE_PLUGIN=NO' \
            --show-output
