name: Benchmark

on:
  push:

permissions:
  contents: read

concurrency:
  group: benchmark-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  benchmark-cache:
    name: Benchmark Tuist Cache
    runs-on: namespace-profile-default-macos
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Authenticate Tuist
        working-directory: xcode_project_with_cache
        run: TUIST_URL="https://staging.tuist.dev" tuist auth login --email tuistrocks@tuist.dev --password ${{ secrets.TUIST_TEST_ACCOUNT_PASSWORD }}

      - name: Setup Tuist Cache
        working-directory: xcode_project_with_cache
        run: tuist setup cache

      # - name: Clone Tuist Repository
      #   run: git clone https://github.com/tuist/tuist tuist

      # - name: Setup Tuist Cache
      #   working-directory: tuist
      #   run: swift run tuist setup cache --path ../xcode_project_with_cache

      # Benchmark 1: Clean build with cache uploads
      - name: Benchmark clean build with cache uploads
        working-directory: xcode_project_with_cache
        run: |
          hyperfine --warmup 1 --runs 10 \
            --prepare 'rm -rf ~/Library/Developer/Xcode/DerivedData && ../tuist-setup-temp-project && tuist setup cache' \
            --conclude '../tuist-cleanup-temp-project' \
            'ORG=$(cat .tuist-temp-org) && PROJECT=$(cat .tuist-temp-project) && xcodebuild -project App.xcodeproj -scheme App -destination "platform=iOS Simulator,name=iPhone 17" build COMPILATION_CACHE_REMOTE_SERVICE_PATH="$ORG/$PROJECT"' \
            --show-output

      # Benchmark 2: Clean build with pre-warmed cache
      - name: Benchmark clean build with pre-warmed cache
        working-directory: xcode_project_with_cache
        run: |
          hyperfine --warmup 1 --runs 10 \
            --setup 'xcodebuild -project App.xcodeproj -scheme App -destination "platform=iOS Simulator,name=iPhone 17" build' \
            --prepare 'rm -rf ~/Library/Developer/Xcode/DerivedData' \
            'xcodebuild -project App.xcodeproj -scheme App -destination "platform=iOS Simulator,name=iPhone 17" build' \
            --show-output

      # Benchmark 3: Clean build without caching
      - name: Benchmark clean build without caching
        working-directory: xcode_project_with_cache
        run: |
          hyperfine --warmup 1 --runs 10 \
            --prepare 'rm -rf ~/Library/Developer/Xcode/DerivedData' \
            'xcodebuild -project App.xcodeproj -scheme App -destination "platform=iOS Simulator,name=iPhone 17" build COMPILATION_CACHE_ENABLE_CACHING=NO' \
            --show-output

      # Benchmark 3: Clean build with local caching
      - name: Benchmark clean build with local caching
        working-directory: xcode_project_with_cache
        run: |
          hyperfine --warmup 1 --runs 10 \
            --setup 'rm -rf ~/Library/Developer/Xcode/DerivedData' \
            --prepare 'xcodebuild -project App.xcodeproj -scheme App -destination "platform=iOS Simulator,name=iPhone 17" clean' \
            'xcodebuild -project App.xcodeproj -scheme App -destination "platform=iOS Simulator,name=iPhone 17" build COMPILATION_CACHE_ENABLE_PLUGIN=NO' \
            --show-output

  benchmark-mastodon-ios:
    name: Benchmark Mastodon iOS
    runs-on: namespace-profile-default-macos
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Authenticate Tuist
        working-directory: mastodon-ios
        run: TUIST_URL="https://staging.tuist.dev" tuist auth login --email tuistrocks@tuist.dev --password ${{ secrets.TUIST_TEST_ACCOUNT_PASSWORD }}

      - name: Setup Tuist Cache
        working-directory: mastodon-ios
        run: tuist setup cache

      # Benchmark 1: Clean build with cache uploads
      - name: Benchmark clean build with cache uploads
        working-directory: mastodon-ios
        run: |
          hyperfine --warmup 1 --runs 5 \
            --prepare 'rm -rf ~/Library/Developer/Xcode/DerivedData && ../tuist-setup-temp-project' \
            --conclude '../tuist-cleanup-temp-project' \
            'xcodebuild -project Mastodon.xcodeproj -scheme Mastodon -destination "platform=iOS Simulator,name=iPhone 17" build' \
            --show-output

      # Benchmark 2: Clean build with pre-warmed cache
      - name: Benchmark clean build with pre-warmed cache
        working-directory: mastodon-ios
        run: |
          hyperfine --warmup 1 --runs 5 \
            --setup '../tuist-setup-temp-project && xcodebuild -project Mastodon.xcodeproj -scheme Mastodon -destination "platform=iOS Simulator,name=iPhone 17" build' \
            --prepare 'rm -rf ~/Library/Developer/Xcode/DerivedData' \
            --conclude '../tuist-cleanup-temp-project' \
            'xcodebuild -project Mastodon.xcodeproj -scheme Mastodon -destination "platform=iOS Simulator,name=iPhone 17" build' \
            --show-output

      # Benchmark 3: Clean build without caching
      - name: Benchmark clean build without caching
        working-directory: mastodon-ios
        run: |
          hyperfine --warmup 1 --runs 5 \
            --prepare 'rm -rf ~/Library/Developer/Xcode/DerivedData' \
            'xcodebuild -project Mastodon.xcodeproj -scheme Mastodon -destination "platform=iOS Simulator,name=iPhone 17" build COMPILATION_CACHE_ENABLE_CACHING=NO' \
            --show-output

      # Benchmark 4: Clean build with local caching
      - name: Benchmark clean build with local caching
        working-directory: mastodon-ios
        run: |
          hyperfine --warmup 1 --runs 5 \
            --setup 'rm -rf ~/Library/Developer/Xcode/DerivedData' \
            --prepare 'xcodebuild -project Mastodon.xcodeproj -scheme Mastodon -destination "platform=iOS Simulator,name=iPhone 17" clean' \
            'xcodebuild -project Mastodon.xcodeproj -scheme Mastodon -destination "platform=iOS Simulator,name=iPhone 17" build COMPILATION_CACHE_ENABLE_PLUGIN=NO' \
            --show-output
