name: Benchmark

on:
  push:

permissions:
  contents: read

concurrency:
  group: benchmark-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  benchmark-cache:
    name: Benchmark Tuist Cache
    runs-on: namespace-profile-default-macos
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Authenticate Tuist
        working-directory: xcode_project_with_cache
        run: CI=false TUIST_URL="https://canary.tuist.dev" tuist auth login --email tuistrocks@tuist.io --password ${{ secrets.TUIST_TEST_ACCOUNT_PASSWORD }}

      - name: Setup Tuist Cache
        working-directory: xcode_project_with_cache
        run: CI=false tuist setup cache

      # Benchmark 1: Clean build with cache uploads
      - name: Benchmark clean build with cache uploads
        working-directory: xcode_project_with_cache
        run: |
          CI=false hyperfine --warmup 1 --runs 3 \
            --prepare 'rm -rf ~/Library/Developer/Xcode/DerivedData && mise run tuist-setup-temp-project' \
            --conclude 'mise run tuist-cleanup-temp-project' \
            'xcodebuild -project App.xcodeproj -scheme App -destination "platform=iOS Simulator,name=iPhone 17" build' \
            --show-output

      # Benchmark 2: Clean build with pre-warmed cache
      - name: Benchmark clean build with pre-warmed cache
        working-directory: xcode_project_with_cache
        run: |
          hyperfine --warmup 1 --runs 3 \
            --setup 'mise run tuist-setup-temp-project && xcodebuild -project App.xcodeproj -scheme App -destination "platform=iOS Simulator,name=iPhone 17" build' \
            --prepare 'rm -rf ~/Library/Developer/Xcode/DerivedData' \
            --conclude 'mise run tuist-cleanup-temp-project' \
            'xcodebuild -project App.xcodeproj -scheme App -destination "platform=iOS Simulator,name=iPhone 17" build' \
            --show-output

      # Benchmark 3: Clean build without caching
      - name: Benchmark clean build without caching
        working-directory: xcode_project_with_cache
        run: |
          hyperfine --warmup 1 --runs 3 \
            --prepare 'rm -rf ~/Library/Developer/Xcode/DerivedData' \
            'xcodebuild -project App.xcodeproj -scheme App -destination "platform=iOS Simulator,name=iPhone 17" build COMPILATION_CACHE_ENABLE_CACHING=NO' \
            --show-output

      # Benchmark 3: Clean build with local caching
      - name: Benchmark clean build with local caching
        working-directory: xcode_project_with_cache
        run: |
          hyperfine --warmup 1 --runs 3 \
            --setup 'rm -rf ~/Library/Developer/Xcode/DerivedData' \
            'xcodebuild -project App.xcodeproj -scheme App -destination "platform=iOS Simulator,name=iPhone 17" build COMPILATION_CACHE_ENABLE_PLUGIN=NO' \
            --show-output
