name: Benchmark Tuist Cache

on:
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: benchmark-tuist-cache-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  cache-uploads:
    name: Clean build with cache uploads
    runs-on: namespace-profile-default-macos
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Authenticate Tuist
        working-directory: tuist
        run: TUIST_URL="https://staging.tuist.dev" tuist auth login --email tuistrocks@tuist.dev --password ${{ secrets.TUIST_TEST_ACCOUNT_PASSWORD }}

      - name: Install dependencies
        working-directory: tuist
        run: tuist install

      - name: Benchmark clean build with cache uploads
        working-directory: tuist
        run: |
          hyperfine --warmup 1 --runs 3 \
            --prepare 'rm -rf ~/Library/Developer/Xcode/DerivedData && tuist clean binaries' \
            'tuist cache && tuist generate TuistApp && xcodebuild -workspace TuistApp.xcworkspace -scheme TuistApp build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO' \
            --show-output

  pre-warmed:
    name: Clean build with pre-warmed cache
    runs-on: namespace-profile-default-macos
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Authenticate Tuist
        working-directory: tuist
        run: TUIST_URL="https://staging.tuist.dev" tuist auth login --email tuistrocks@tuist.dev --password ${{ secrets.TUIST_TEST_ACCOUNT_PASSWORD }}

      - name: Install dependencies
        working-directory: tuist
        run: tuist install

      - name: Warm cache
        working-directory: tuist
        run: tuist cache

      - name: Benchmark clean build with pre-warmed cache
        working-directory: tuist
        run: |
          hyperfine --warmup 1 --runs 3 \
            --prepare 'rm -rf ~/Library/Developer/Xcode/DerivedData && tuist clean binaries' \
            'tuist generate TuistApp && xcodebuild -workspace TuistApp.xcworkspace -scheme TuistApp build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO' \
            --show-output

  no-cache:
    name: Clean build without caching
    runs-on: namespace-profile-default-macos
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Authenticate Tuist
        working-directory: tuist
        run: TUIST_URL="https://staging.tuist.dev" tuist auth login --email tuistrocks@tuist.dev --password ${{ secrets.TUIST_TEST_ACCOUNT_PASSWORD }}

      - name: Install dependencies
        working-directory: tuist
        run: tuist install

      - name: Benchmark clean build without caching
        working-directory: tuist
        run: |
          hyperfine --warmup 1 --runs 3 \
            --prepare 'rm -rf ~/Library/Developer/Xcode/DerivedData && tuist clean binaries' \
            'tuist generate TuistApp && xcodebuild -workspace TuistApp.xcworkspace -scheme TuistApp build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO' \
            --show-output

  local-cache:
    name: Clean build with local caching
    runs-on: namespace-profile-default-macos
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Authenticate Tuist
        working-directory: tuist
        run: TUIST_URL="https://staging.tuist.dev" tuist auth login --email tuistrocks@tuist.dev --password ${{ secrets.TUIST_TEST_ACCOUNT_PASSWORD }}

      - name: Install dependencies
        working-directory: tuist
        run: tuist install

      - name: Benchmark clean build with local caching
        working-directory: tuist
        run: |
          hyperfine --warmup 1 --runs 3 \
            --setup 'tuist cache' \
            --prepare 'rm -rf ~/Library/Developer/Xcode/DerivedData && tuist clean binaries' \
            'tuist generate TuistApp && xcodebuild -workspace TuistApp.xcworkspace -scheme TuistApp build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO' \
            --show-output